# Generated by Django 5.2.4 on 2025-07-14 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuelos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_city', models.CharField(max_length=200)),
                ('departure_city', models.CharField(max_length=200)),
                ('passengers', models.IntegerField()),
                ('departure_date', models.DateField()),
                ('comeback_date', models.DateField()),
                ('type_flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type', to='vuelos.typeflights')),
            ],
        ),
    ]
